### ISSUE TITLE
user profile updates

### ISSUE THREAD

**Issue by MichaelJob** [MichaelJob/ThatsAppSpecEmobaHS21#11]
Wenn ich "meinen" user nickname ändere, dann publishe ich die UserMsg nochmals mit der gleichen id auf users/id. Der Webclient erhält die Nachricht. Meine App scheint sie nicht zu kriegen... Es geht prima, wenn ich meinen user vom webclient aus absende, wenn ich einen anderen User vom Webclient aus publishe, dann kriege ich den auch rein, sende ich den gleichen nochmals mit neuem nickname, funktioniert auch das update. Sehe grad nicht wieso mein Profile-Update nicht geht... hat jemand vielleicht eine Idee?

**Comment by juerggnos** [comment]
Ohne Zugriff auf den Code ist eine Analyse schwierig. Scheint auf den ersten Blick aber ein seltsames Verhalten zu sein. Ich starte heute mit der Umsetzung meiner App und melde mich wieder sobald ich mit dem Profilscreen soweit bin. Dann kann ich vielleicht weiterhelfen.

**Comment by sirtoobii** [comment]
Ich hab grad ziemlich lang an einem sehr ähnlichen (identischen?) Problem gekämpft: Wenn ich vom Client eine message an seinen notification channel gesendet habe bekommt er keine Notification, wird eine message vom einem anderen Client als er selbst gesendet kommt die Notfication an.
Ich denke das ist ein Feature: **Der Sender bekommt keine eigenen Nachrichten!**

**Comment by MichaelJob** [comment]
Not a bug, it's a feature. - Das erklärts, hat mich bei den Messages nicht gestört, da ich die selbst versendeten Messages intern gleich speichere... demfall beim Profile update auch so zu handhaben.
PS: merry x-mas
