### ISSUE TITLE
Profilepic

### ISSUE THREAD

**Issue by MichaelJob** [MichaelJob/ThatsAppSpecEmobaHS21#13]
wie machen wir das mit den Profilbildern? via file.io ist es im Gratisplan nur einmal downloadbar - wenn mehrere User bspw. mein Profilbild laden wollen, dann müssten wir das anders lösen... ev. bitmap als byte[] direkt versenden? oder bleiben wir beim sharen einer url? dann lade ich das Profilbild auf einen anderen Host als file.io

**Comment by sirtoobii** [comment]
Ich würde beim URL bleiben und beim (da ein Profilbild auch keine Anforderung ist) und im Profil-Editor kann man ja im einfachsten Fall einfach ein Link zu einem Bild einstellen.

**Comment by juerggnos** [comment]
Gemäss README ist "Profile-Screen mit Name und Avatar-Bild" gewünschte Funktionalität. Würde daher vorschlagen, dass wir uns auf die im Projekt eingecheckten Avatar-Bilder beschränken. Anstatt der URL des Bildes könnte dann der Filename angegeben werden. Wahrscheinlich wäre es dann auch sinnvoll das Attribut userImage required zu machen.

**Comment by MichaelJob** [comment]
> Gemäss README ist "Profile-Screen mit Name und Avatar-Bild" gewünschte Funktionalität. Würde daher vorschlagen, dass wir uns auf die im Projekt eingecheckten Avatar-Bilder beschränken. Anstatt der URL des Bildes könnte dann der Filename angegeben werden. Wahrscheinlich wäre es dann auch sinnvoll das Attribut userImage required zu machen.

hmm, ich würde gerne bei der url bleiben, damit man beliebige Images einstellen kann - ev. können wir in diesem Feld aber auch die lokalen Minions Avatar ids als String mitgeben, als Fallback für die Apps, die keine url verwenden - dann müssten diese Apps einfach bei nicht erkennen eines lokalen Avatars (weil url gesendet wurde) ein default Avatar wählen. Die Apps die urls fetchen, könnten dann diese Bilder auslesen, oder eben auch ein lokales Avatar anzeigen. Somit hätten wir beides?

**Comment by juerggnos** [comment]
Passt für mich. Und Attribut userImage required, einverstanden?
