### ISSUE TITLE
Benützen von git tags für Spec Version

### ISSUE THREAD

**Issue by sirtoobii** [MichaelJob/ThatsAppSpecEmobaHS21#14]
Aus praktischen Gründen würde ich Vorschlagen, im `version`-property nicht den commit-hash zu verwenden sondern ein git tag. Im Zuge dessen würde ich für die Tags "semantic versioning" verwenden.

Einwände oder Bemerkungen?

**Comment by MichaelJob** [comment]
Ist es realistisch, dass wir dann verschiedene Ausbaustufen haben werden? Wie setzt man das in der App um? Werden alle MQTT Nachrichten die nicht mit dem richtigen Tag kommen ignoriert? Wäre es nicht einfacher auf einem allgemein gültigen Stand zu bestehen? Sollten sich dann doch zwei oder drei Versionen (Tags) ergeben, dann könnte man einen spezifischen MQTT Endpunkt pro Version definieren, damit sich pro MainTopic nur kompatible Apps miteinander austauschen? Also ev. das "thatsapp01cc" zu einem "thatsapp01ccv1", "thatsapp01ccv2" machen... (falls es überhaupt nötig wird). ((Meine App versendet momentan eine version, aber ignoriert das intern komplett.))

**Comment by sirtoobii** [comment]
Hmm, das mit den einzeln Topics klingt zwar in der theorie sehr "sauber" aber ich denke das gibt nur ein "xstürm" - Ich denke wir könnten eigentlich im Readme noch schreiben "Es ist Sache des clients mit unsupporteten nachrichten umzugehen"
