### ISSUE TITLE
broker

### ISSUE THREAD

**Issue by MichaelJob** [MichaelJob/ThatsAppSpecEmobaHS21#4]
Wieso ist der Broker auf "broker.mqttdashboard.com" definiert und nicht wie bei der Flutter_Solution auf val "broker.hivemq.com" ? Mit dem WebClient kann man auf beide verbinden. Spielt also ev. keine Rolle.

Vorschlag:

    val mqttBroker = "broker.hivemq.com"
    val mainTopic  = "fhnw/emoba/thatsapp01cc"

**Comment by sirtoobii** [comment]
Ja, passt für mich
